- name: update pacman packages
  hosts: clientes
  become: yes

  tasks:
    - name: update keyring to prevent signing errors
      community.general.pacman:
        name: archlinux-keyring
        state: latest
        update_cache: true
    - name: update system via -Syu
      community.general.pacman:
        update_cache: true
        upgrade: true

