- name: update pacman packages
  hosts: clientes
  become: yes

  tasks:
    - name: update keyring to prevent signing errors
      pacman:
        name: archlinux-keyring
        state: latest
        update_cache: true
    - name: update system via -Syu
      pacman:
        update_cache: true
        upgrade: true
    - name: keep cache trimmed
      command: paccache -rk3
      
